using ComHe_Objets;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace ComHe_Pilotage {

    public partial class frmPrincipale : DevExpress.XtraEditors.XtraForm {
        public List<Segment> segments { get; set; }
        public frmPrincipale() {
            segments = new List<Segment>();
            segments.Add(new Segment("Segment A", enumTypeSegment.INDIV, 35000, 0.5, 0.6, 2000, 0.3, 0.25));
            segments.Add(new Segment("Segment B", enumTypeSegment.BNC, 3000, 0.2, 0.3, 500, 0.5, 0.36));
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            vGridControl1.DataSource = new System.Collections.Generic.List<ComHe_Objets.Segment>(segments);
        }

        private void chartControl1_Click(object sender, EventArgs e) {

        }

        private void button1_Click(object sender, EventArgs e) {

        }
    }
}
